# Project: NOIP
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = NOIP_private.res
OBJ      = main.o T.o $(RES)
LINKOBJ  = main.o T.o $(RES)
LIBS     = -L"H:/softwares/Dev-Cpp/MinGW64/lib" -L"H:/softwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"H:/softwares/Dev-Cpp/MinGW64/include" -I"H:/softwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"H:/softwares/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"H:/softwares/Dev-Cpp/MinGW64/include" -I"H:/softwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"H:/softwares/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"H:/softwares/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = NOIP.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

T.o: T.cpp
	$(CPP) -c T.cpp -o T.o $(CXXFLAGS)

NOIP_private.res: NOIP_private.rc 
	$(WINDRES) -i NOIP_private.rc --input-format=rc -o NOIP_private.res -O coff 

